import {
  cultural1,
  cultural2,
  cultural3,
  cultural4,
  cultural5,
  cultural6,
  pooja1,
  pooja10,
  pooja2,
  pooja3,
  pooja4,
  pooja5,
  pooja6,
  pooja7,
  pooja8,
  pooja9,
  temple1,
  temple2,
  temple3,
  temple4,
  temple5,
  temple6,
  temple7,
  temple8,
} from "@/assets/images";

export const activitiesImages = {
  pooja: [
    {
      id: 1,
      src: pooja1,
      alt: "Pooja Image 1",
      caption: "Pooja Image 1",
      height: "720",
      width: "1080",
    },
    {
      id: 2,
      src: pooja2,
      alt: "Pooja Image 2",
      caption: "Pooja Image 2",
      height: "720",
      width: "1080",
    },
    {
      id: 3,
      src: pooja3,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 4,
      src: pooja4,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 5,
      src: pooja5,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 6,
      src: pooja6,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 7,
      src: pooja7,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 8,
      src: pooja8,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 9,
      src: pooja9,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 10,
      src: pooja10,
      alt: "Pooja Image 3",
      caption: "Pooja Image 3",
      height: "720",
      width: "1080",
    },
  ],
  culturals: [
    {
      id: 11,
      src: cultural1,
      alt: "Cultural Image 1",
      caption: "Cultural Image 1",
      height: "720",
      width: "1080",
    },
    {
      id: 12,
      src: cultural2,
      alt: "Cultural Image 2",
      caption: "Cultural Image 2",
      height: "720",
      width: "1080",
    },
    {
      id: 13,
      src: cultural3,
      alt: "Cultural Image 3",
      caption: "Cultural Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 14,
      src: cultural4,
      alt: "Cultural Image 4",
      caption: "Cultural Image 4",
      height: "720",
      width: "1080",
    },
    {
      id: 15,
      src: cultural5,
      alt: "Cultural Image 5",
      caption: "Cultural Image 5",
      height: "720",
      width: "1080",
    },
    {
      id: 16,
      src: cultural6,
      alt: "Cultural Image 6",
      caption: "Cultural Image 6",
      height: "720",
      width: "1080",
    },
  ],
  temple: [
    {
      id: 17,
      src: temple1,
      alt: "Temple Image 1",
      caption: "Temple Image 1",
      height: "720",
      width: "1080",
    },
    {
      id: 18,
      src: temple2,
      alt: "Temple Image 2",
      caption: "Temple Image 2",
      height: "720",
      width: "1080",
    },
    {
      id: 19,
      src: temple3,
      alt: "Temple Image 3",
      caption: "Temple Image 3",
      height: "720",
      width: "1080",
    },
    {
      id: 20,
      src: temple4,
      alt: "Temple Image 4",
      caption: "Temple Image 4",
      height: "720",
      width: "1080",
    },
    {
      id: 21,
      src: temple5,
      alt: "Temple Image 5",
      caption: "Temple Image 5",
      height: "720",
      width: "1080",
    },
    {
      id: 22,
      src: temple6,
      alt: "Temple Image 6",
      caption: "Temple Image 6",
      height: "720",
      width: "1080",
    },
    {
      id: 23,
      src: temple7,
      alt: "Temple Image 7",
      caption: "Temple Image 7",
      height: "720",
      width: "1080",
    },
    {
      id: 24,
      src: temple8,
      alt: "Temple Image 8",
      caption: "Temple Image 8",
      height: "720",
      width: "1080",
    },
  ],
};
